name: new_ovacs
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dartz: ^0.10.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  image_picker: ^1.1.2
  device_preview: ^1.3.1
  flutter_svg: ^2.2.0
  pinput: ^5.0.1
  url_launcher: ^6.3.1
  file_picker: ^10.2.0
  open_filex: ^4.7.0
  permission_handler: ^12.0.1
  http: ^1.4.0
  iconsax: ^0.0.8
  table_calendar: ^3.2.0
  provider: ^6.1.5
  equatable: ^2.0.7
  just_audio: ^0.10.4
  record: ^6.0.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  path: ^1.9.1
  rxdart: ^0.28.0
  http_parser: ^4.1.2
  ffmpeg_kit_flutter_new: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Fustat
      fonts:
        - asset: assets/fonts/Fustat/Fustat-Bold.ttf
        - asset: assets/fonts/Fustat/Fustat-ExtraBold.ttf
        - asset: assets/fonts/Fustat/Fustat-ExtraLight.ttf
        - asset: assets/fonts/Fustat/Fustat-Light.ttf
        - asset: assets/fonts/Fustat/Fustat-Medium.ttf
        - asset: assets/fonts/Fustat/Fustat-Regular.ttf
        - asset: assets/fonts/Fustat/Fustat-SemiBold.ttf
flutter_intl:
  enabled: true
